### ISSUE TITLE
What do you think having drivers available in inject callback ?

### ISSUE THREAD

**Issue by bpetetot** [alakarteio/k-ramel#109]
I have opened a question, because I don't know if it's the philosophy of the library, but I think it could be useful in some cases.

**Simple example :**
```js
import { inject } from '@k-ramel/react'
import MyComponent from './myComponent'

inject((store, props, { router }) => ({
   id: router.getParam('id'),
   onClick: () => router.push('/mypath')
}))(MyComponent)
```

**Comment by fabienjuif** [comment]
You are right the philisophy is about listeners.
But we can make it if you think this is a **must have**.

**Comment by EmrysMyrddin** [comment]
Yes, this kind of things should be in listeners.

But since it's given as their parameter, after props, I think it's ok. And it can be really useful in simple apps where you don't acre that mutch to separate concerns at this extreme level.

**Comment by fabienjuif** [comment]
If you need this feel free to open a PR 👍
If you are needed this, don't open a PR.

Keep it simple, we should think like this: "I need this I wrote this", not like this "Maybe someone will need this".

**Comment by bpetetot** [comment]
I may need to think again about my use cases. I may don't need it, I have to check my app design with k-ramel.

**Comment by fabienjuif** [comment]
Finally I need this for selectors 🤡
