### ISSUE TITLE
devTools / Use Trace option

### ISSUE THREAD

**Issue by guillaumecrespel** [alakarteio/k-ramel#260]
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Features/Trace.md

**Comment by fabienjuif** [comment]
Add an option createStore to set it: https://github.com/alakarteio/k-ramel/blob/master/packages/k-ramel/doc/STORE.md#create-store

(and update the linked documentation)

Default value should be false to begin with since it appears to degrade performances
