### ISSUE TITLE
driver-http / add context to request

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-ramel#264]
API:
 - `http('TITLE', { id: 1, whatever: 42 }).get('url')`
    * type: `@@http/TITLE>GET>ENDED`
    * payload: `<response payload>`
    * status: `<response status>`
    * context: `{ id: 1, whatever: 42 }`
 - `http('TITLE').get('url')`
    * type: `@@http/TITLE>GET>ENDED`
    * payload: `<response payload>`
    * status: `<response status>`
    * context: undefined

**Comment by guillaumecrespel** [comment]
why not add the context on second and optional parameter ? 
> http('TITLE', { id: 1, whatever: 42 }).get('url')

Because `TITLE` is already a "context" no ?

**Comment by fabienjuif** [comment]
Ok, I update the first comment
