### ISSUE TITLE
Use something like `stockroom` ?

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-ramel#28]
Use this: https://github.com/developit/stockroom
Or reimplement the idea ?

**Comment by bpetetot** [comment]
https://github.com/developit/greenlet from the same author could be useful if it's reimplemented

**Comment by fabienjuif** [comment]
The issue with webworker is that you pay for what you give and retrieve.
Since we give all the store to our reactions, I think it would cost a lot.

But we can give it a try

**Comment by fabienjuif** [comment]
I tried on a simple function:
 - it cost at least 150ms (chrome/firefox)

I tried an a big function:
 - it works on chrome, but it was not worth it for my use case
 - it doesn't work on firefox (I don't dig into it), maybe because of webpack transpilation ? I don't know, and this is hard to debug a web worker.

I don't think this is a good idea right know to add greenelt

**Comment by fabienjuif** [comment]
see previous comment
