### ISSUE TITLE
Get the header of the HTTP response

### ISSUE THREAD

**Issue by jeromemenard** [alakarteio/k-ramel#281]
Hello. Can we get the header of the HTTP response with the driver '@k-ramel/driver-http driver'?

**Comment by fabienjuif** [comment]
I will add a `headers` field in the action dispatched by `ENDED` and `FAILED`.

From here I have 2 options to serialize the headerss
### Object
```js
{
  connection: "close"
  "content-length": "393"
  "content-type": "application/json; charset=utf-8"
  date: "Mon, 14 Jan 2019 10:31:00 GMT"
​  vary: "Accept-Encoding"
​  "x-powered-by": "Express"
}
```

You can access header by: `action.headers["x-powered-by"]`

### Arrays (Map)
```js
[
  [
    "connection",
    "close"
  ],
  [
    "content-length",
    "393"
  ],
  [
    "content-type",
    "application/json; charset=utf-8"
  ],
  [
    "date",
    "Mon, 14 Jan 2019 10:33:44 GMT"
  ],
  [
    "vary",
    "Accept-Encoding"
  ],
  [
    "x-powered-by",
    "Express"
  ]
]
```

You can access header by: `new Map(action.headers).get("x-powered-by")`

**Comment by jeromemenard** [comment]
I prefer option number 1 but let you choose the easiest option to implement. Thank you very much.

**Comment by fabienjuif** [comment]
Ok, I'll write option 1.

I think we'll publish a 1.3.0 version this evening.

**Comment by fabienjuif** [comment]
nevermind, I don't know about this evening, I have a breaking change in an other PR :(
I'll keep you in touch @jeromemenard
