### ISSUE TITLE
Disable devtools in production

### ISSUE THREAD

**Issue by frinyvonnick** [alakarteio/k-ramel#292]
We experienced [an issue on NantesJS website](https://github.com/NantesJS/nantesjs-website/issues/61) about devtools enable no matter the current env. What do you think of disabling it in production ?

**Comment by fabienjuif** [comment]
I don't know how to handle env variables in a lib.
You can enable/disable it on your own:

`createStore(definition, { devtools: process.env.NODE_END !== 'production' })`
https://github.com/alakarteio/k-ramel/blob/master/packages/k-ramel/src/createStore/enhanceRedux/getDevTools.js#L12

Side note: The devtools should not be connected if there is no devtools extension in your browser: https://github.com/alakarteio/k-ramel/blob/master/packages/k-ramel/src/createStore/enhanceRedux/getDevTools.js#L7
