### ISSUE TITLE
Question/discussion: optics.lens and other considerations

### ISSUE THREAD

**Issue by cateland** [alakarteio/k-ramel#63]
seeing the example here

https://github.com/alakarteio/k-simple-state#create-a-simple-store

wouldn't be a good idea to ditch the imperative api to on dispatching lense to the reducers ?

and using the same lense to select the data from the store so it can be used in map state to props etc. ?

Many other toughts store enhancer seems to be a better fit than wrapping a redux store, maybe all this can be achieved using a higher order reducer to and avoid creating a knowledge gap between mainstream redux api and tools (like connect).

**Comment by fabienjuif** [comment]
Hi, thank you for the interest :)

One think about this lib is that it is still compatible with Redux.
You can still use `connect`, use your known `enhancer`/`middlewares`, your known `reducers` and your custom one.

An other advantage passing by Redux `dispatch` and `selectors` is to have access to the Redux event bus, so we can listen to modifications. (See listeners: https://github.com/alakarteio/k-simple-state/blob/master/examples/todomvc/src/store/listeners/index.js)

That being said, I keep in mind this idea to use lenses to avoid calling `get/set/etc`

**Comment by fabienjuif** [comment]
@cateland Can we speak about this out of loud ?
Maybe tomorrow evening at NantesJS ?

I close the issue for now.
