### ISSUE TITLE
Throw a readable exception when using inject in a react tree without provider

### ISSUE THREAD

**Issue by EmrysMyrddin** [alakarteio/k-ramel#73]
For now, when you forgot to use the `provider` HOC in your application, it throws cryptic error :

![image](https://user-images.githubusercontent.com/3855602/36200376-c34d720a-117c-11e8-8e6c-81dfe00ce55f.png)

I suggest to have a more cleaner exception with a hint for the developer and a link to the documentation.

**Comment by fabienjuif** [comment]
Do you want to open the associate PR ?

**Comment by EmrysMyrddin** [comment]
Yes, I will do it this afternoon.

**Comment by EmrysMyrddin** [comment]
Do you already have some sort of clean error reporting ? I'm a bit lost and don't see anything to display a clean error in the console.

**Comment by fabienjuif** [comment]
I just have that in mind: https://github.com/alakarteio/hoc-little-router/blob/master/src/router.jsx#L42
