### ISSUE TITLE
Handle an empty return from inject parameter

### ISSUE THREAD

**Issue by EmrysMyrddin** [alakarteio/k-ramel#82]
An error is thrown if the function given to `inject` return somehting else than an object.

The simplest example to reproduce :
```es6
inject(() => {})(Component)
```

Should this trhow an error ? A warning ? Nothing ?

**Comment by fabienjuif** [comment]
I don't like the fact that we have to control each error than can occurs if the API is not respected.
Because this is a bunch of `if` to add for developpement time only (and that will be triggered in production times)

**Comment by EmrysMyrddin** [comment]
I agree that all the cases doesn't have to be handled. Juste the one or tow that have a lots of chance to occur.

And for now, you can't let errors as it is. Since the source mapping doesn't works, it leaves the developper alone with a cryptic error without any idea of what's happening.

**Comment by fabienjuif** [comment]
Yes I agree.
Maybe we have to fix source mapping in first place ?

**Comment by EmrysMyrddin** [comment]
Yes, source mapping have to be fixed. It will clean up a litle the errors.
